module.exports = {
	//首页
	GET_TRANINEELIST:'GET_TRANINEELIST',//获取学员列表
	GET_STUDYING_STATUS:'GET_STUDYING_STATUS',//获取学习中的详情
	GET_STUDENT_DETAIL:'GET_STUDENT_DETAIL',//获取学员详情
	UPDATE_LEADS_DETAIL:'UPDATE_LEADS_DETAIL',//更新意向
	DELETE_LEADS_STUDENT:'DELETE_LEADS_STUDENT',//删除意向
	GET_APP_SIGNUP_INFO:'GET_APP_SIGNUP_INFO',//报名下拉信息
	SUBMIT_STUDENT_INFO:'SUBMIT_STUDENT_INFO',//报名表单提交
	ADD_STUDENT_NOTE:'ADD_STUDENT_NOTE',//添加学员笔记
	AUPDATE_STUDENT_NOTE:'AUPDATE_STUDENT_NOTE',//更新学员笔记
	STUDENT_NOTE_DETAIL:'STUDENT_NOTE_DETAIL',//学员笔记详情
	STUDENT_NOTE_LIST:'STUDENT_NOTE_LIST',//学员笔记列表
	GET_ALL_CARS_TYPE:'GET_ALL_CARS_TYPE',//获取所有车型列表
	GET_CLASS_LISTS:'GET_CLASS_LISTS',//获取班型列表
	DELETE_CLASS_TYPE_ITEM:'DELETE_CLASS_TYPE_ITEM',//删除班型
	COMPLETE_CARD_INFO:'COMPLETE_CARD_INFO',//完善教练信息
	UPDATE_CLASS_TYPE:'UPDATE_CLASS_TYPE',//修改班型
	GET_CAOCH_INFO:'GET_CAOCH_INFO',//获取教练信息
	GET_CARD_SERVICE:'GET_CARD_SERVICE',//获取服务列表
	UPDATE_COACH_INFO:'UPDATE_COACH_INFO',//修改教练信息
	GET_APP_VERSION_INSTALL:'GET_APP_VERSION_INSTALL',//检查app是否更新
	SHARE_ENCRYPT_INFOMATION:'SHARE_ENCRYPT_INFOMATION',//分享请求微信qq
	UPDATE_MONEY_DETAIL:'UPDATE_MONEY_DETAIL',//编辑上传金额

	GET_AUTHENTICATION_BY_CODE:'GET_AUTHENTICATION_BY_CODE',//通过验证码登录
	GET_AUTHENTICATION_BY_WXQQ:'GET_AUTHENTICATION_BY_WXQQ',//通过微信登录
	GET_MY_TRADE_INDEX:'GET_MY_TRADE_INDEX',//钱包
	GET_AUTHENTICATION_BY_PWD:'GET_AUTHENTICATION_BY_PWD',//通过密码登录
	REMOVE_TOKEN:'REMOVE_TOKEN',//删除登录状态,
	CHECK_CODE:'CHECK_CODE',
	GET_USERACCOUNTLIST_BY_PLATFORM:'GET_USERACCOUNTLIST_BY_PLATFORM',
	UPDATE_THIRD_STATUS:'UPDATE_THIRD_STATUS',
	GET_MY_USER_APPINFO:'GET_MY_USER_APPINFO',//个人中心
	GET_MY_USER_USER_ACCOUNT:'GET_MY_USER_USER_ACCOUNT',//设置页
	GET_MY_USER_CODE:'GET_MY_USER_CODE',//更换手机号-步骤一-获取验证码
	GET_MY_USER_CHECK_FLRSTCHANGEMOBLIE_CODE:'GET_MY_USER_CHECK_FLRSTCHANGEMOBLIE_CODE',//更换手机号-步骤二-校验当前绑定手机验证码
	GET_MY_USER_NEWCODE:'GET_MY_USER_NEWCODE',//更换手机号-步骤三-获取新手机号验证码
	GET_MY_USER_CHANGE_MOBILE:'GET_MY_USER_CHANGE_MOBILE',//更换手机号-步骤四-保存并验证新手机号码
	GET_MY_USER_CHANGE_HEADIMG:'GET_MY_USER_CHANGE_HEADIMG',//修改头像
	GET_MY_USER_BIND_THIRDACCOUNT:'GET_MY_USER_BIND_THIRDACCOUNT',//绑定第三方授权账号(绑定微信)
	GET_MY_USER_CHANGE_THIRDACCOUNT_STATUS:'GET_MY_USER_CHANGE_THIRDACCOUNT_STATUS',//解绑第三方授权账号(解绑微信)
	GET_MY_NOTICE_GET_LISTS:'GET_MY_NOTICE_GET_LISTS',//消息列表（版本/学员)
	GET_MY_NOTICE_UPDATE_LOG:'GET_MY_NOTICE_UPDATE_LOG',//点击查看，取消红点
	GET_MY_NOTICE_GETSTATUS:'GET_MY_NOTICE_GETSTATUS',//底部红点
	GET_PUB_USER_LOGOUT:'GET_PUB_USER_LOGOUT',//退出登录
	GET_APPLY_APP_URL:'GET_APPLY_APP_URL',//热更新
	GET_SCHOOL_LIST:'GET_SCHOOL_LIST',//驾校列表
	SET_CONFIG:'SET_CONFIG',//
	GET_CONFIG:'GET_CONFIG',//
	UPDATE_CONFIG:'UPDATE_CONFIG',//存储登陆信息
	REMOVE_CONFIG:'REMOVE_CONFIG',//
	UPDATE_DEFAULT_SCHOOL:'UPDATE_DEFAULT_SCHOOL',//更新默认驾校
	CHOOSE_SCHOOL_LOGIN:'CHOOSE_SCHOOL_LOGIN',//登录成功后选择的驾校

	GET_BUSINESS_MY_NOTICE_LISTS:'GET_BUSINESS_MY_NOTICE_LISTS',//消息列表
	GET_BUSINESS_MY_USER_SETTLEMENT_LIST:'GET_BUSINESS_MY_USER_SETTLEMENT_LIST',//我的账单
    GET_BUSINESS_MY_NOTICE_STATUS:'GET_BUSINESS_MY_NOTICE_STATUS',//是否有新消息
	GET_BUSINESS_MY_ADVISORY_CREATE:'GET_BUSINESS_MY_ADVISORY_CREATE',//意见反馈
	
	UPDATE_USER_STUDY:'UPDATE_USER_STUDY',//修改成绩的接口






	GET_CODE_BY_PHONE:'GET_CODE_BY_PHONE',//通过手机获取短信验证码
	REGISTER:'REGISTER',//注册
	LOGIN:'LOGIN',//登录
	
}